name: Jacked Vulnerability Scanner
description: Jacked Vulnerability Scanner - GitHub Action.
author: Carbonetes
inputs:
  scan-name:
    description: 'Image name, Tar File Path, or Directory Path.'
    required: true
  scan-type:
    description: 'Type "image", "tar", or "directory".'
    required: true
  fail-criteria:
    description: 'Optionally specify the minimum vulnerability severity to trigger an "error".  Valid choices are "negligible", "low", "medium", "high" and "critical".'
    required: false
  skip-build-fail:
    description: 'Set build is always success, ignore assessment result.'
    required: false
    default: "false"
  skip-db-update:
    description: 'Skip Jacked Vulnerability Database Update'
    required: false
    default: "false"
  ignore-package-names:
    description: 'Ignore Package names when scanning... e.g. input: dpkg,tar,bash,...'
    required: false
  ignore-cves:
    description: 'Ignore CVES when scanning... e.g. input: CVE-2022-1271,CVE-2022-3715,CVE-2022-1664,...'
    required: false
  
runs:
  using: node16
  main: dist/main.js
