name: Jacked Scan
description: Jacked GitHub Action Vulnerability Scanner.
author: Carbonetes
inputs:
  directory:
    description: The path directory to scan.
    required: true
  fail-criteria:
    description: 'Optionally specify the minimum vulnerability severity to trigger an "error".  Valid choices are "negligible", "low", "medium", "high" and "critical".'
    required: false
runs:
  using: node16
  main: index.js
