name: Compile TypeScript and Commit Files to Pull Request
on:
  pull_request:
    types:
      - opened
      - synchronize
 
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Compile TypeScript and Commit Files to Pull Request

    steps: 
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Install Dependencies
        run: npm install

      - name: Install Type Declarations for Node.js
        run: npm install --save-dev @types/node

      - name: Compile TypeScript
        run: npx tsc --outDir src src/main.ts

      - name: Set Up Git Config
        run: |
          git config user.email "${{ secrets.EMAIL }}"
          git config user.name "${{ secrets.USERNAME }}"
          git config --global credential.helper "store --file=$HOME/.git-credentials"
          echo "https://github.com/${{ secrets.USERNAME }}:${{ secrets.ACCESS_TOKEN }}" >> $HOME/.git-credentials

          
      - name: Commit and Push Changes
        run: | 
          git add .
          git commit -m "chore: Compile TypeScript files"
          git remote set-url origin "https://github.com/carbonetes/jacked-action.git"
          git push origin HEAD:refs/heads/${{ github.head_ref }}
