name: Compile TypeScript and Commit Files to Pull Request
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Compile TypeScript and Commit Files to Pull Request

    steps: 
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Install Dependencies
        run: npm install

      - name: Install Type Declarations for Node.js
        run: npm install --save-dev @types/node

      - name: Compile TypeScript
        run: npx tsc --outDir src src/main.ts

      - name: Set Up Git Config
        run: |
          git config user.email "${{ secrets.EMAIL }}"
          git config user.name "${{ secrets.USERNAME }}"
          
      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Compile TypeScript files"
          git push origin HEAD:${{ github.ref }}

