name: Compile TypeScript
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish GitHub Action

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Install Type Declarations for Node.js
        run: npm install --save-dev @types/node

      - name: Compile TypeScript
        run: npx tsc

      - name: Commit Changes
        run: |
          git add .
          git commit -m "Compile TypeScript"
          git push
